#!/bin/sh
target=$1
rcfile=$HOME/.config/jtnrc

if [ -f $rcfile -a "$target" ]; then
    for dictfile in `cat $rcfile`; do
        grep "$target" $dictfile;
    done
else
    echo "Usage: jtn <word>"
    echo "(Please list your dictionaries in $HOME/.config/jtnrc, one filename per line.)"
    exit 1
fi
